'actions':
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
# For now, all other changes are considered vscode extension changes, in the future we can split to workspaces
'extension: vscode':
  - changed-files:
      - any-glob-to-any-file:
        - '**/*'
