name: Format

on:
  workflow_dispatch:
  push: 
    branches: 
      - main

jobs:
  format:
    if: ${{ github.repository_owner == 'hadez8877' }}
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      -  name: Setup git commiter
         id: commiter
         uses: ./.github/actions/setup-git-commiter
         with:
           pascal-client-id: ${{ vars.PASCAL_CLIENT_ID }}
           pascal-app-secret: ${{ secrets.PASCAL_APP_SECRET }}

      - name: setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.18.0

      - name: Format code
        run: pnpm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_user_name: ${{ steps.commiter.outputs.app-slug }}[bot]
          commit_user_email: ${{ steps.commiter.outputs.app-slug }}[bot]@users.noreply.github.com
          commit_author: ${{ github.event.commits[0].author.name }} <${{ github.actor }}@users.noreply.github.com>
